### ISSUE TITLE
link in author info is not shown

### ISSUE THREAD

**Issue by psychomuell** [pkollitsch/wp-tropicalisland#10]
if i add a read-more link to my author footer it is not shown on the website

**Comment by pkollitsch** [comment]
It appears this is about the more-tag. not sure how to "fix" it.

**Comment by pkollitsch** [comment]
solution depends on gambitph/Titan-Framework#393

**Comment by pkollitsch** [comment]
won't fix this one. the read more link is solely for for post types and not for an option field. you need to create a post or page and add an excerpt to the author option field with a full link to the post/page.
