### ISSUE TITLE
Pingbacks

### ISSUE THREAD

**Issue by psychomuell** [pkollitsch/wp-tropicalisland#13]
The possibility to output Pingbacks (collected) above the comments

**Comment by pkollitsch** [comment]
Pingbacks and Trackbacks are disabled in wp-tropicalisland. Enabling them would be easy, but then the comments would have to be inside of the "normal" comments list. Adding an extra Pingback list on top of "real" comments would mean to traverse the comments twice, once for pingbacks, once for everything but pingbacks. Not sure if that's in line with our need for speed here.

**Comment by pkollitsch** [comment]
Won't fix this.
