### ISSUE TITLE
Author Foto

### ISSUE THREAD

**Issue by psychomuell** [pkollitsch/wp-tropicalisland#14]
The possibility to upload (intern) an article author foto without using gravatar ...

ups, better pull requests ...

**Comment by pkollitsch** [comment]
This is a "won't fix" ;)

The ability to upload an author photo is a WordPress internal function. if they decide that it has to be via Gravatar, then go to Gravatar and set up a separate Gravatar for your BlogURL. You can add arbitrary Gravatars per domain in one single account. Go check it out ;)

**Comment by pkollitsch** [comment]
closed
